ssh

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,65 +5,65 @@ on:
     branches:
       - main
 
-# jobs:
-#   deploy:
-#     runs-on: ubuntu-latest
-
-#     steps:
-#       - name: Checkout code
-#         uses: actions/checkout@v2
-
-#       - name: Setup Node.js
-#         uses: actions/setup-node@v2
-#         with:
-#           node-version: '14'
-
-#       - name: Install dependencies
-#         run: npm ci
-
-#       - name: Build the app
-#         run: npm run build
-
-#       - name: Deploy to server
-#         uses: appleboy/ssh-action@master
-#         with:
-#           host: ${{ secrets.SERVER_HOST }}
-#           username: ${{ secrets.SERVER_USERNAME }}
-#           password: ${{ secrets.SERVER_PASSWORD }}
-#           port: 22
-#           script: |
-#             cd /home/theop/html/drama
-#             if [ "$(pwd)" = "/home/theop/html/drama" ]; then
-#               echo "dir found"
-#               rm -rf *
-#               scp -r "${{ github.workspace }}/build/" .
-#             else
-#               echo "Error: Script not running in the expected directory." >&2
-#               exit 1
-#             fi
-
-
 jobs:
-  build-and-deploy:
+  deploy:
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Install dependencies and build
-        run: |
-          npm ci
-          npm run build
-
-      - name: Test Files
-        run: ls
-
-      - name: Deploy to server via FTP
-        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
+      - name: Setup Node.js
+        uses: actions/setup-node@v2
         with:
-          server: ${{ secrets.SERVER_HOST }}
+          node-version: '14'
+
+      - name: Install dependencies
+        run: npm ci
+
+      - name: Build the app
+        run: npm run build
+
+      - name: Deploy to server
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USERNAME }}
           password: ${{ secrets.SERVER_PASSWORD }}
-          local-dir: ./build/
-          server-dir: /home/theop/html/drama/
+          port: 22
+          script: |
+            cd /home/theop/html/drama
+            if [ "$(pwd)" = "/home/theop/html/drama" ]; then
+              echo "dir found"
+              rm -rf *
+              scp -r "${{ github.workspace }}/usr/bin/bash/build/" .
+            else
+              echo "Error: Script not running in the expected directory." >&2
+              exit 1
+            fi
+
+
+# jobs:
+#   build-and-deploy:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v2
+
+#       - name: Install dependencies and build
+#         run: |
+#           npm ci
+#           npm run build
+
+#       - name: Test Files
+#         run: ls
+
+#       - name: Deploy to server via FTP
+#         uses: SamKirkland/FTP-Deploy-Action@v4.3.4
+#         with:
+#           server: ${{ secrets.SERVER_HOST }}
+#           username: ${{ secrets.SERVER_USERNAME }}
+#           password: ${{ secrets.SERVER_PASSWORD }}
+#           local-dir: ./build/
+#           server-dir: /home/theop/html/drama/
