own

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,27 +27,27 @@ jobs:
       - name: Test files
         run: ls
 
-      - name: Deploy to server
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.SERVER_HOST }}
-          username: ${{ secrets.SERVER_USERNAME }}
-          password: ${{ secrets.SERVER_PASSWORD }}
-          port: 22
-          script: |
-            cd /home/theop/html/drama
-            if [ "$(pwd)" = "/home/theop/html/drama" ]; then
-              echo "dir found"
-              rm -rf *
-              scp -r /usr/bin/bash/build/* .
-            else
-              echo "Error: Script not running in the expected directory." >&2
-              exit 1
-            fi
-      # - name: Deploy to server via SSH
-      #   run: |
-      #     echo "${{ secrets.SERVER_PASSWORD }}" | scp -r -o StrictHostKeyChecking=no -B ./build ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/theop/html/drama
-
+      # - name: Deploy to server
+      #   uses: appleboy/ssh-action@master
+      #   with:
+      #     host: ${{ secrets.SERVER_HOST }}
+      #     username: ${{ secrets.SERVER_USERNAME }}
+      #     password: ${{ secrets.SERVER_PASSWORD }}
+      #     port: 22
+      #     script: |
+      #       cd /home/theop/html/drama
+      #       if [ "$(pwd)" = "/home/theop/html/drama" ]; then
+      #         echo "dir found"
+      #         rm -rf *
+      #         scp -r /usr/bin/bash/build/* .
+      #       else
+      #         echo "Error: Script not running in the expected directory." >&2
+      #         exit 1
+      #       fi
+      - name: Deploy to server via SSH
+        run: |
+          scp -r build ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/theop/html/drama
+          echo ${{ secrets.SERVER_PASSWORD }} 
 
 # jobs:
 #   build-and-deploy:
